apiVersion: v1
kind: PersistentVolume
metadata:
  name: volume-1
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 1Gi
  accessModes:
  - ReadWriteOnce
  hostPath:
    path: "/pv/data"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongodb-claim
spec:
  storageClassName: manual
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: db-deployment
  labels:
    app: mongodb
spec:
  selector:
    matchLabels:
      app: mongodb
  replicas: 1
  template:
    metadata:
      labels:
        app: mongodb
    spec:
      volumes:
      - name: db-storage
        persistentVolumeClaim:
          claimName: mongodb-claim

      containers:
      - name: mongodb
        image: mongo
        ports:
        - name: mongodb
          containerPort: 27017
        volumeMounts:
        - name: db-storage
          mountPath: "/data/db"
---
apiVersion: v1
kind: Service
metadata:
  name: db-service
spec:
  selector:
    app: mongodb
  ports:
  - port: 27017
    targetPort: mongodb
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-deployment
  labels:
    app: redis
spec:
  selector:
    matchLabels:
      app: redis
  replicas: 1
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
      - name: redis
        image: redis
        ports:
        - name: redis-port
          containerPort: 6379
---
apiVersion: v1
kind: Service
metadata:
  name: redis-service
spec:
  selector:
    app: redis
  ports:
  - port: 6379
    targetPort: redis-port
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: zookeeper-deployment
  labels:
    app: zookeeper
spec:
  selector:
    matchLabels:
      app: zookeeper
  replicas: 1
  template:
    metadata:
      labels:
        app: zookeeper
    spec:
      containers:
      - name: zookeeper
        image: zookeeper
        ports:
        - name: zookeeper-port
          containerPort: 2181
---
apiVersion: v1
kind: Service
metadata:
  name: zookeeper-service
spec:
  selector:
    app: zookeeper
  ports:
  - port: 2181
    targetPort: zookeeper-port
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: election-deployment
  labels:
    app: election
spec:
  selector:
    matchLabels:
      app: election
  replicas: 3
  template:
    metadata:
      labels:
        app: election
    spec:
      containers:
      - name: leader-election-container
        image: mridulsahu/leader-election:1.0
        env:
        - name: DB_URI
          value: "db-service:27017"
        - name: REDIS_URI
          value: "redis-service:6379"
        - name: ZOOKEEPER_URI
          value: "zookeeper-service:2181"
---
